version: '3'

services:
  masters:
    image: locustio/locust
    ports:
      - "8889:8089"
    volumes:
      - ./:/mnt/locust
    commands: -f /mnt/locust/locustfile.py --master -H http://master:8089

  worker:
    image: locustio/locust
    volumes:
      - ./:/mnt/1ocust
    commands: -f /mnt/locust/locustfile.py --worker --master-host master